services:
  fastapi:
    build: .
    container_name: signaling-server-api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_LEVEL=info
      - ROOM_EXPIRE=300
    depends_on:
      - redis
    networks:
      - signaling-server-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    container_name: signaling-server-redis
    networks:
      - signaling-server-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
      image: nginx:alpine
      container_name: signaling-server-nginx
      depends_on:
        - fastapi
      ports:
        - "8090:80" # You can change the port to any available port (change the left one)
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      networks:
        - signaling-server-network
      restart: unless-stopped
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "3"

networks:
  signaling-server-network:
    driver: bridge
